// Auth
// export const AUTH = "AUTH";
// export const CHECK_AUTH_TIMEOUT = "CHECK_AUTH_TIMEOUT";
// Mine Auth
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_REGISTER = "AUTH_REGISTER";
export const SUCCESS_AUTH = "SUCCESS_AUTH";
export const FAIL_AUTH_LOGIN = "FAIL_AUTH_LOGIN";
export const FAIL_AUTH_REGISTER = "FAIL_AUTH_REGISTER";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
// UI
export const LOADING_LOGIN = "LOADING_LOGIN";
export const LOADING_SIGNUP = "LOADING_SIGNUP";
// payment
export const ADD_PAYMENT = "ADD_PAYMENT";
export const SUCCESS_ADD_PAYMENT = "SUCCESS_ADD_PAYMENT";
// products
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const SUCCESS_FETCH_PRODUCTS = "SUCCESS_FETCH_PRODUCTS";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const SUCCESS_FETCH_PRODUCT = "SUCCESS_FETCH_PRODUCT";

// bid
export const SEND_BID = "SEND_BID";
export const SUCCESS_SEND_BID = "SUCCESS_SEND_BID";

// export const LOADING_SEARCH = "LOADING_SEARCH";

// DB
// export const FETCH_POSTS = "FETCH_POSTS";
// export const FETCH_IMAGES = "FETCH_IMAGES";
// export const SUCCESS_FETCH_IMAGES = "SUCCESS_FETCH_IMAGES";
// export const SUCCESS_FETCH_POSTS = "SUCCESS_FETCH_POSTS";
// export const FETCH_USER = "FETCH_USER";
// export const SUCCESS_FETCH_USER = "SUCCESS_FETCH_USER";
// export const FETCH_NEWS = "FETCH_NEWS";
// export const SUCCESS_FETCH_NEWS = "SUCCESS_FETCH_NEWS";
// export const FAILED_FETCH_POSTS = "FAILED_FETCH_POSTS";
// export const SEND_NEW_POST = "SEND_NEW_POST";
// export const SUCCESS_SEND_NEW_POST = "SUCCESS_SEND_NEW_POST";
// export const ADD_COMMENT = "ADD_COMMENT";
// export const SUCCESS_ADD_COMMENT = "SUCCESS_ADD_COMMENT";
// export const FETCH_USERS = "FETCH_USERS";
// export const SUCCESS_FETCH_USERS = "SUCCESS_FETCH_USERS";
// export const TOGGLE_LOVE = "TOGGLE_LOVE";
// export const SUCCESS_TOGGLE_LOVE = "SUCCESS_TOGGLE_LOVE";
// export const CANCEL = "CANCEL";
// export const DECLINE = "DECLINE";
// export const ACCEPT = "ACCEPT";
// export const FOLLOW = "FOLLOW";
// export const UNFOLLOW = "UNFOLLOW";
// export const SUCCESS_FOLLOW_SYSTEM = "SUCCESS_FOLLOW_SYSTEM";
// export const LOADING_SEND_POST = "LOADING_SEND_POST";
// export const LOADING_SEND_COMMENT = "LOADING_SEND_COMMENT";
// export const LOADING_FETCH_POSTS = "LOADING_FETCH_POSTS";
// export const CHANGE_AVATAR = "CHANGE_AVATAR";
// export const SUCCESS_CHANGE_AVATAR = "SUCCESS_CHANGE_AVATAR";
// export const CHANGE_COVER = "CHANGE_COVER";
// export const SUCCESS_CHANGE_COVER = "SUCCESS_CHANGE_COVER";
// export const LOADING_CHANGE_PIC = "LOADING_CHANGE_PIC";
// export const LOADING_FETCH_USERS = "LOADING_FETCH_USERS";
// export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
// export const SEARCH_USER = "SEARCH_USER";
// export const SUCCESS_SEARCH_USER = "SUCCESS_SEARCH_USER";
// export const USER_NOT_FOUND = "USER_NOT_FOUND";
// export const RESET_SCROLL_PAGE = "RESET_SCROLL_PAGE";
// export const CURRENT_USER = "CURRENT_USER";
