// Auth
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_REGISTER = "AUTH_REGISTER";
export const SUCCESS_AUTH = "SUCCESS_AUTH";
export const FAIL_AUTH_LOGIN = "FAIL_AUTH_LOGIN";
export const FAIL_AUTH_REGISTER = "FAIL_AUTH_REGISTER";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
// UI
export const LOADING_LOGIN = "LOADING_LOGIN";
export const LOADING_SIGNUP = "LOADING_SIGNUP";
// payment
export const ADD_PAYMENT = "ADD_PAYMENT";
export const SUCCESS_ADD_PAYMENT = "SUCCESS_ADD_PAYMENT";
// products
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const SUCCESS_FETCH_PRODUCTS = "SUCCESS_FETCH_PRODUCTS";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const SUCCESS_FETCH_PRODUCT = "SUCCESS_FETCH_PRODUCT";
export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PAGE_COUNT = "UPDATE_PAGE_COUNT";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const SUCCESS_SEARCH_PRODUCTS = "SUCCESS_SEARCH_PRODUCTS";
// profile
export const FETCH_PROFILE = "FETCH_PROFILE";
export const SUCCESS_FETCH_PROFILE = "SUCCESS_FETCH_PROFILE";

// bid
export const SEND_BID = "SEND_BID";
export const SUCCESS_SEND_BID = "SUCCESS_SEND_BID";

// Wallet
export const FETCH_WALLET = "FETCH_WALLET";
export const SUCCESS_FETCH_WALLET = "SUCCESS_FETCH_WALLET";
