export {
  successAuth,
  // auth,
  authLogout,
  authLogoutSucceed,
  // checkAuthTimeout,
  authCheckState,
  failLogin,
  failRegister,
  // currentUser,
  authLogin,
  authRegister,
  fetchProducts,
  successFetchProducts,
  addPayment,
  successAddPayment,
  fetchProduct,
  successFetchProduct,
  sendBid,
  successSendBid,
  uploadImage,
  createProduct,
} from "./auth/index";

export { loadingLogin, loadingSignup } from "./ui/index";
